name: Deploy to server

on: push # Trigger the workflow on push events
jobs:
  first_jobs:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    steps:
      - name: Hola mundo
        run: echo "Hola mundo desde el primer job"


  second_jobs:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    steps:
      - name: Hola mundo 2
        run: echo "Hola mundo desde el primer job"      
        