name: "Hola mundo"
on:
  push:
    branches: ["main"]
jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    step:
      uses: actions/checkout@v4
      run: echo "Hacemos pull del codigo"
      run: echo "Instalamos dependencias"
      run: echo "Compilamos el codigo"
